name: Build Nintendont (produce boot.dol)

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fix modern GCC strict errors
        run: |
          echo "CFLAGS += -Wno-error=incompatible-pointer-types" >> multidol/Makefile

      - name: Run Build Script
        run: |
          ./Build.sh

      - name: Prepare boot.dol
        run: |
          if [ -f "loader/loader.dol" ]; then
            cp loader/loader.dol boot.dol
          else
            cp $(find . -type f -iname '*.dol' -print -quit) boot.dol
          }
          ls -lh boot.dol

      - name: Upload boot.dol artifact
        uses: actions/upload-artifact@v4
        with:
          name: boot.dol
          path: boot.dol
